# Generated by Django 2.1.4 on 2018-12-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions', '0002_auto_20181218_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starreditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='starreditem',
            unique_together={('user', 'object_id', 'content_type')},
        ),
    ]
