# Generated by Django 2.1.4 on 2018-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181220_0909'),
        ('questions', '0003_profile'),
    ]

    operations = [
    ]
