# Generated by Django 2.1.4 on 2018-12-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_merge_20181221_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resolved',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_question', to='questions.Answer'),
        ),
    ]
