# Generated by Django 2.1.4 on 2018-12-26 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_merge_20181221_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
    ]
