# Generated by Django 2.1.4 on 2018-12-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='star',
            new_name='starred',
        ),
    ]
