# Generated by Django 2.1.4 on 2018-12-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='resolved',
            field=models.OneToOneField(limit_choices_to={'answers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_question', to='questions.Answer'),
        ),
    ]
