# Generated by Django 2.1.4 on 2018-12-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181223_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='resolved',
        ),
        migrations.AddField(
            model_name='answer',
            name='resolving_answer',
            field=models.OneToOneField(limit_choices_to={'answers': 'Resolved Answer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_question', to='questions.Answer'),
        ),
    ]
