# Generated by Django 2.1.4 on 2018-12-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181223_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolve',
            name='resolved_question',
        ),
        migrations.RemoveField(
            model_name='resolve',
            name='valid_answer',
        ),
        migrations.DeleteModel(
            name='Resolve',
        ),
    ]
