# Generated by Django 2.1.4 on 2018-12-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20181223_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolve',
            name='resolving_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_answer', to='questions.Answer'),
        ),
    ]
