# Generated by Django 2.1.4 on 2018-12-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181223_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='resolving_answer',
        ),
    ]
