# Generated by Django 2.1.4 on 2018-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_question_resolving_answer'),
        ('questions', '0006_auto_20181226_0755'),
    ]

    operations = [
    ]
